policies:
  - name: KerasPolicy
    epochs: 400
    max_history: 5
  - name: FallbackPolicy
    fallback_action_name: 'utter_default'
  - name: MemoizationPolicy
    max_history: 5
  - name: FormPolicy